### ISSUE TITLE
How do we treat Transiting state

### ISSUE THREAD

**Issue by nickjer** [OSC/ood_job#11]
How do we treat the PBS/Torque Transiting `T` state? Suggestions:

- `:queued`
- `:queued_held`
- `:undetermined`

Right now it falls under `:undetermined` so the app will think the job is completed. I am not 100% sure what the Transiting state is, but I can cause a job to enter this state using `qmove`. I haven't tested moving a job between queues, but I can cause a job to be in the `T` state indefinitely with a move to a different batch server.

**Comment by ericfranz** [comment]
:queued_held makes sense to me

**Comment by ericfranz** [comment]
Though unfortunately for active jobs it seems like it would be preferable to display the word Transitioning instead of Held

**Comment by nickjer** [comment]
I forgot, `:suspended` is an option as well (although when I think of suspended I think it was `:running` but then got `:suspended`).

One possibility is we add a new state that has a corresponding value in SLURM and LSF...

This is SLURM:

>JOB STATE CODES
>
>Jobs typically pass through several states in the course of their execution. The typical states are PENDING, RUNNING, SUSPENDED, COMPLETING, and COMPLETED. An explanation of each state follows.
**BF BOOT_FAIL**
Job terminated due to launch failure, typically due to a hardware failure (e.g. unable to boot the node or block and the job can not be requeued).
**CA CANCELLED**
Job was explicitly cancelled by the user or system administrator. The job may or may not have been initiated.
**CD COMPLETED**
Job has terminated all processes on all nodes with an exit code of zero.
**CF CONFIGURING**
Job has been allocated resources, but are waiting for them to become ready for use (e.g. booting).
**CG COMPLETING**
Job is in the process of completing. Some processes on some nodes may still be active.
**F FAILED**
Job terminated with non-zero exit code or other failure condition.
**NF NODE_FAIL**
Job terminated due to failure of one or more allocated nodes.
**PD PENDING**
Job is awaiting resource allocation.
**PR PREEMPTED**
Job terminated due to preemption.
**R REVOKED**
Sibling was removed from cluster due to other cluster starting the job.
**R RUNNING**
Job currently has an allocation.
**SE SPECIAL_EXIT**
The job was requeued in a special state. This state can be set by users, typically in EpilogSlurmctld, if the job has terminated with a particular exit value.
**ST STOPPED**
Job has an allocation, but execution has been stopped with SIGSTOP signal. CPUS have been retained by this job.
**S SUSPENDED**
Job has an allocation, but execution has been suspended and CPUs have been released for other jobs.
**TO TIMEOUT**
Job terminated upon reaching its time limit.

This is LSF:

> JOB STATUS
      Possible values for the status of a job include:
      **PEND** The job is pending, that is, it has not yet been started.
      **PSUSP**
	   The job has been suspended, either by its owner or the LSF
	   administrator, while pending.
      **RUN**  the job is currently running.
      **USUSP**
	   The job has been suspended, either by its owner or the LSF
	   administrator, while running.
      **SSUSP**
	   The job has been suspended by LSF due to either of the following
	   two causes: 1) The load conditions on the execution host or hosts
	   have exceeded a threshold according to the loadStop vector
	   defined for the host or queue or 2) the run window of the job's
	   queue is closed.
	   (See bqueues(1), bhosts(1), and lsb.queues(5).)
      **DONE** The job has terminated with status of 0.
      **EXIT** The job has terminated with a non-zero status - it may have been
	   aborted due to an error in its execution, or killed by its owner
	   or the LSF administrator.
      **UNKWN**
	   The master batch daemon (mbatchd) has lost contact with the slave
	   batch daemon (sbatchd) on the host on which the job runs.
      **ZOMBI**
	   A job will become ZOMBI if:
	   1) the job is killed by bkill command while the sbatchd on the
	   execution host is unreachable and the job is shown as UNKWN,
	   2) the host on which a rerunnable job is running is unavailable
	   and the job has been requeued by LSF with a new job ID, as if the
	   job were submitted as a new job.
	   After the execution host becomes available,	LSF will try to kill
	   the ZOMBI job.  Upon successful termination of the ZOMBI job,
	   the job's status will be changed to EXIT.
	   In an LSF MultiCluster environment,	when a job running on a
	   remote execution cluster becomes a ZOMBIE job,  the execution
	   cluster will treat the job the same way as local ZOMBIE jobs.  In
	   addition, it notifies the submission cluster that the job is in
	   ZOMBIE state and the submission cluster requeues the job.

Another possibility is we add a `:transiting` state, and the method `#transiting?` will always return `false` for every other resource manager outside of Torque.

**Comment by ericfranz** [comment]
Addressed in 5f7956436208914647b984b911a662591b9ea9be
