### ISSUE TITLE
Add job name and account to OodJob::Info

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_job#12]
We are currently building LSF and Slurm adapters. These (and probably future adapters) should support the ability to get:

1. job name
2. account that a job is charged to

**Comment by nickjer** [comment]
I agree with this, we just need to document that the relevant attributes exist when retrieving job status information from the various resource managers. But I am fairly confident these both exist for LSF as well as Slurm.

**Comment by nickjer** [comment]
Moved to https://github.com/OSC/ood_core/issues/2
