### ISSUE TITLE
Add way for adapter's to customize attribute titles for job info

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_job#13]
1. LSF calls an account a job is charged to a "Project".
2. Torque calls an account a job is charged to an "Account".

Should we provide a way for an adapter to provide customized string for a title?

One solution would be to do:

Adapter#info_attr_title(:attr_name)

The default could be to titleize this symbol. The adapter could override for special cases (such as `:account`). An app like ActiveJobs could do something like `adapter.info_attr_title(:account)`.

That said, we haven't had any complaints yet when using `Account` at OSC on the Active Jobs app while we typically refer to these accounts as "Projects".

So we should probably ignore this disparity for now.

**Comment by nickjer** [comment]
I think we should leave it up to the app developers on how they want to display this information. For example, in VNCSim I use:

![image](https://cloud.githubusercontent.com/assets/4260509/24207760/1baf24bc-0ef8-11e7-9902-99a331a1cc1c.png)

even though we use Torque.
