### ISSUE TITLE
Add to status object done and failed state

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_job#2]
Currently, if a job is completed, we return `:undetermined` because the resource manager no longer knows about this job.

However, we could imagine a future where a resource manager did know about previously run jobs (or a custom TorqueAdapter, for instance), that would be able to tell both that the job specified by the id did in fact run in the past and is now done and determine the exit status of that job.

An OSC specific example that is possible in the future:

1. Systems provides users access to views of the pbsacct so they can query past job information
2. An OSCTorqueAdapter does qstat first, and if the job is not available, then queries the pbsacct to get the job exit status. Of course, the job would need to stay in the "completed" state on Torque until the record was added to pbsacct, or else we would risk returning "undetermined" for such a job.

However, because I don't know of any other resource managers that actually provide this ability, and we currently don't provide this ability either, perhaps it is not appropriate to add these here.

One caveat is that an adapter would only be allowed to return these values if they always returned these values for the provided completed job id. For example, our current TorqueAdapter would not return this, because it doesn't have access to the exit status and because Torque holds onto a job in the "C" state for only a short time.

**Comment by ericfranz** [comment]
Another problem with this is that if some adapters never return `:done` and `:failed` states, that means the caller has to deal with inconsistencies between adapters. For example, the caller would have to know if the adapter returns `:undetermined` in the case of a completed job and then handle this by assuming it is `:done` and then try to determine whether or not the job exited with a non-zero status by inspecting the output files (which is what we do now). But then if another adapter returned `:failed` or `:done` the caller would need to know this so `:undetermined` would then be an actual problem.

* `:undetermined` would then mean two different things based on the adapter's abilities

Because of this, we cannot allow adapters to return `:completed` or `:failed`. Instead, if an adapter provides this information (like the exit status), it must be accessed by querying adapter specific attributes.

So we will not add these values to `OodJob::Status`.

**Comment by nickjer** [comment]
I can see some of these cases getting an OSC specific wrapper. Example:

```ruby
class OSCStatus < OodJob::Status
    # Possibly change the below into something more modifiable instead of a constant
    STATES = %i(
      queued
      queued_held
      running
      suspended
      requeued
      requeued_held
      does_not_exist
      done
      failed
    )
end

class OSCTorque < OodJob::Adapters::Torque
  ...

  def status(id:)
    char = pbs.get_job(id, filters: [:job_state])[id][:job_state]
    OSCStatus.new(state: STATE_MAP.fetch(char))
  rescue PBS::UnkjobidError
    # Handle PBSACCT stuff here...
    # and return either...
    # OSCStatus.new(state: :done) or OSCStatus.new(state: :failed) or OSCStatus.new(state: :does_not_exist)
  rescue PBS::Error => msg
    raise Error, msg
  end
end
```

**Comment by ericfranz** [comment]
In this example, `undetermined` is being replaced by `does_not_exist`, `done`, and `failed`. The Rails app would need to be modified to handle this status appropriately. Then the Rails app could not be configured to use different adapters because different adapters would not know how to convert `OodJob::Status` to `OSCStatus` unless we provided a default conversion.

However, perhaps ood_job_rails could have: 

```ruby
class OodJobRails::Status < OodJob::Status
  STATES = %i(does_not_exist done passed failed).append(OodJob::Status::STATES)
end
```

or something similar, since ood_job_rails has code to decide what the state of a job and/or the workflow is once we have `OodJob::Status#undetermined?`

**Comment by nickjer** [comment]
I am leaning towards going back to a `Job` active record model as an STI. That way you can have something like...

```ruby
class Job < ActiveRecord::Base
  enum status: [:not_submitted, :queued, :queued_held, :running, :suspended, :completed]
  enum result: [:passed, :failed]    # passed? will be default true

  # Setup `#completed` callback
  define_model_callbacks :completed
  def completed
    run_callbacks :completed do
      self.completed!
    end
  end

  ...
end

class MainJob < Job
  belongs_to :container, foreign_key: :workflow_id, inverse_of: :main_job

  after_completed :validate_main_job

  def validate_main_job
    # Code here...
    if passed_checks
      self.passed!
    else
      self.failed!
    end
  end

  ...
end
```

So for a running job...

```ruby
@container.main_job.status #=> "running"
@container.main_job.running? #=> true
@container.main_job.completed? #=> false
```

and for a completed job...

```ruby
@container.main_job.status #=> "completed"
@container.main_job.completed? #=> true

@container.main_job.result #=> "failed"
@container.main_job.passed? #=> false
@container.main_job.failed? #=> true
```

The above will still have the odd situation where `passed?` is true no matter the status...

```ruby
@container.main_job.status #=> "running"
@container.main_job.running? #=> true
@container.main_job.completed? #=> false
@container.main_job.passed? #=> true
```

A couple ways around that is overriding the `#passed?` method to return `false` if `#completed?` is `false`. Or creating another `result` option that is default like `:no_result` (but then we'd have to call `#passed!` when transition the status of the job to `#completed!`).

**Comment by nickjer** [comment]
Using STI for `Job` we can also scan all the jobs belonging to a workflow irrespective of the inherited class type:

```ruby
class Workflow < ActiveRecord::Base
  ...

  def stop
    ...
    Job.where(workflow_id: id).each |job|
      # stop the job
    end
    ...
  end

  def update_status
    ...
    Job.where(workflow_id: id).each |job|
      # status the job
    end
    ...
  end
end

class Container < Workflow
  has_one :main_job
  has_one :post_job

  ...
end
```

Although some thought will need to go into when to create the main_job and post_job model objects in the container. I know in Machete you don't create them until you submit the job, but in most of my cases I needed them before as they hold user submitted job properties (i.e., walltime, number of cores, ...), so they were created in the `ContainersController#new`.
