### ISSUE TITLE
Consider using resource_mgr_server instead of cluster as argument to Adapter initializer

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_job#7]
This is the currently documentation:

```ruby
# Get the Oakley cluster object from OodAppkit
oak = OodAppkit.clusters['oakley']

# Use this cluster object to submit the script (be sure you choose the correct
# adapter to communicate with this cluster)
adapter = OodJob::Adapters::Torque.new(cluster: oak)

# Submit your script
adapter.submit(script: script)
#=> "1234.server"
```

In `OodJob::Adapters::Torque` cluster is only used in one place:

```ruby
def pbs
  s = cluster.resource_mgr_server
  PBS::Batch.new(host: s.host, lib: s.lib, bin: s.bin)
end
```
* https://github.com/OSC/ood_job/blob/0f5e06efeb871aaade220b360e4e062f3e23085d/lib/ood_job/adapters/torque.rb#L177-L180

If each adapter will always only use `resource_mgr_server`, it seems more appropriate that we would do this:

```ruby
oak = OodAppkit.clusters['oakley']
adapter = OodJob::Adapters::Torque.new(resource_mgr_server: oak)
````

And then in `OodJob::Adapters::Torque` do

```ruby
def pbs
  s = resource_mgr_server
  PBS::Batch.new(host: s.host, lib: s.lib, bin: s.bin)
end
```

Was the decision to use cluster as the argument out of convenience for the code creating `OodJob::Adapter` instances? Or is there a case where an adapter would call a different method on cluster than resource_mgr_server?

**Comment by nickjer** [comment]
> If each adapter will always only use resource_mgr_server

This is a strong statement that I am not able to guarantee for all future adapters. For instance in `ood_reservations` it required a concerted effort between `resource_mgr_server` and `scheduler_server`. I can't say for certain that the scheduler may not be used by a future `ood_job` adapter, or even some other server supplied by the cluster.

**Comment by ericfranz** [comment]
There is a code smell here.

ood_cluster's role is to provide a list of connection info lists, where a connection info object represents one service. An specific ood_job adapter depends one (or possibly in the future more) services. An example would be an adapter that might use Moab or some some job cache to filter a list of jobs and then use Torque to get details of those jobs. Right now we have simple scenarios where a generic TorqueAdapter will use one connection info object to connect to one service (a single Torque server).

The current solution in OodJob is when instantiating an adapter, we pass in a connection info list and then ask each adapter to know how to pull out of that list the connection info object(s) it needs. This means OodJob adapters each need to know about the connection info object (i.e. ood_cluster object).

If AdapterA needs a single connection info object and AdapterB needs 2 connection info objects it seems that instead of doing:

```ruby
AdapterA.new(conninfolist) # inside the adapter it uses conninfolist.conninfoobject1
AdapterB.new(conninfolist) # inside adapter it uses conninfolist.conninfoobject2 and conninfolist.conninfoobject3
```

we should be doing

```ruby
AdapterA.new(conninfolist.conninfoobject1)
AdapterB.new(conninfolist.conninfoobject2, conninfolist.conninfoobject3)
```

But I understand the goal is that the apps don't have to decide what adapter to instantiate nor know details about each adapter.

**Comment by ericfranz** [comment]
This discussion is no longer relevant. We are going to change things when we switch to the ood_core gem, where every adapter will be instantiated the same way, passing in connection information as appropriate. For a complete discussion on this, see https://github.com/OSC/ood_appkit/issues/36
