### ISSUE TITLE
Torque adapter's `delete` throws unhandled PBS::BadstateError for jobs in "C" state

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_job#8]
For newer versions of Torque, the life cycle of a normal job includes the state "C" and possibly "E". In both these cases, calling the method `OodJob::Adapters::Torque#delete` will result in an unhandled exception thrown: PBS::BadstateError

When the job is no longer in the batch system, we explicitly return nil for `PBS::UnkjobidError` exception from pbs i.e. its not an exceptional case worth keeping. Raising `PBS::BadstateError` when the state is in "C" or "E" is a similar problem. But just ignoring all `PBS::BadstateError` for qdel seems inappropriate. Unless we can safely determine all possible cases that `PBS::BadstateError` would raise for qdel... and determine that none of them are considered "exceptional" for the target audience of ood_job gem.

Here is example output from using shell commands directly:

```
efranz@oakley02:~$ qdel 1833017.oak-batch; echo $?
qdel: nonexistent job id: 1833017.oak-batch
153
efranz@oakley02:~$ qdel 8833077.oak-batch; echo $?
0
efranz@oakley02:~$ qdel 8833077.oak-batch; echo $?
qdel: Request invalid for state of job MSG=invalid state for job - COMPLETE 8833077.oak-batch.osc.edu
170
```

**Comment by ericfranz** [comment]
We could actually just test qdel in all of the states that we think are not exceptional and should return "nil" and add code to handle those situations.

Assuming that the delete message returned is "Request invalid for state of job MSG=invalid state for job - COMPLETE" or "Request invalid for state of job MSG=invalid state for job - EXITING" we could use a regex here.

Seems like something we might forget when future non exceptional states are added to Torque or if these strings change but if that ever happened we could handle those cases then if we run into problems.

**Comment by ericfranz** [comment]
This gets more complex with https://github.com/OSC/ood_job/blob/a755452915ccf818904b9fab6b5d53d28ae90a8f/lib/ood_job/adapters/torque.rb#L8-L14

If we return nil, suggesting that deleting the job succeeded, but the epilogue scripts are still running, there may be implications if we do something like delete PBS_O_WORKDIR directory right after.

**Comment by ericfranz** [comment]
So maybe in this case, the best solution is to not hide this "error" and ask the user to wait a few minutes and try again...

**Comment by ericfranz** [comment]
But then if we do that, we need an OodJob specific way to indicate that.

**Comment by ericfranz** [comment]
So instead of raising an `OodJob::Adapter::Error` we raise an `OodJob::Adapter::TryAgainLater`

**Comment by nickjer** [comment]
I am fine with rescuing `PBS::BadstateError` in `#delete` and having it return `nil`. If we discover a new "bad state" for `qdel` in the future then we will worry about it then.

As for calling `qdel` and deleting the PBS_O_WORKDIR, the developer should not be deleting the workdir **until** he confirms the status of the job is completed, otherwise we will always have that race condition. This unfortunately would make the app a bit more complex and would require more thought.

**Comment by ericfranz** [comment]
So the problem scenario is `PBS::BadstateError` is thrown for a job that is not in exiting or completed state (such as transitioning or suspended). In that case the caller will think that the job deletion worked. However, the job may continue to run after leaving the transitioning or suspended state.

If instead of just returning nil for PBS::BadstateError error we use a regex against the error string to return nil only if the error string includes COMPLETED or EXITING then the problem we have is if the error string changes in future versions of torque. The solution to this is to add an automated test that actually submits a job and deletes the job only after the job has moved into one of these states. But that may be a hard test to write.

**Comment by nickjer** [comment]
Have we tested that we get the `PBS::BadstateError` for transitioning or suspended? I guess it also depends on who suspended the job.

I also think we can reasonably expect the error strings won't change much in future versions. It couldn't hurt to check the Torque source code for older versions and see if the string has been altered over time.

**Comment by nickjer** [comment]
The user should not be deleting the working directory right after they delete a job. The directory should only be deleted on the `Model.all` and `Model.find` calls when it updates the job status and notices the job is completed.

For now I am going to rescue from `PBS::BadstateError` on job deletion because it can cause more trouble now since the `E` state is considered `running? == true`.

**Comment by ericfranz** [comment]
I would feel more comfortable if we only rescued from `PBS::BadstateError` if the error text contained the text "COMPLETE" instead of blindly rescuing from it. I'm concerned that we could get `PBS::BadstateError` in other situations where we would not want to assume the job was successfully deleted.

```
efranz@oakley02:~$ qdel 8833077.oak-batch; echo $?
qdel: Request invalid for state of job MSG=invalid state for job - COMPLETE 8833077.oak-batch.osc.edu
```

> The user should not be deleting the working directory right after they delete a job. The directory should only be deleted on the Model.all and Model.find calls when it updates the job status and notices the job is completed.

That will take more thought, unfortunately. We might change apps and the way we implement them so you cannot "Delete" a running job, and only "Stop" it. Then you could delete a job that has not been submitted or is already completed (i.e. in My Jobs where "Delete" removes the directory). Another option is to have a directory flagged for deletion so it doesn't appear in the app but, like you suggested, delete the directory on `Model#update_status` calls for a directory flagged for deletion. This could be accomplished with a new model state, "deleted" and queries to get a list of models to display to the user could filter out these "deleted" models.

**Comment by ericfranz** [comment]
i.e. `rescue PBS::BadstateError => e` and then check the message, if it has "COMPLETE" etc. we can return nil, else re-raise error

**Comment by nickjer** [comment]
All `PBS::BadstateError`'s return the same message `Request invalid for state of job`. Also calling delete on a job that is Exiting should not raise an error.

**Comment by ericfranz** [comment]
So in other words, using the Torque C API makes it impossible to reproduce the error string that is produced when running `qdel`?

```
efranz@oakley02:~$ qdel 8833077.oak-batch; echo $?
qdel: Request invalid for state of job MSG=invalid state for job - COMPLETE 8833077.oak-batch.osc.edu
170
```

**Comment by nickjer** [comment]
> using the Torque C API makes it impossible to reproduce the error string that is produced when running `qdel`?

Correct.

**Comment by ericfranz** [comment]
How about in the case of this error we actually get the current status of the job and decide to raise the error or return nil as a response

**Comment by nickjer** [comment]
The only time we have observed this error was when a job was in the `E` or `C` state when we tried to delete the job. And in both of these cases it shouldn't raise an exception as the job is currently being deleted or has already been deleted. Note, that if a job is in the `R` state and we call delete on it, we don't raise an exception even though it enters the `E` state right after.

Is there a case you are expecting where we would want to raise an exception?

**Comment by ericfranz** [comment]
Any case we have not yet observed where this error could be raised.

**Comment by nickjer** [comment]
Here is a quick rundown of the code...

User calls `qdel`...

```
     1  *    qdel-command     pbs_server       pbs_mom
     2  *    -------------    -------------    -------------
     3  *          |                |                |
     4  *          +-- DeleteJob -->|                |
     5  *          |                |                |
     6  *          |                +-- DeleteJob -->|
     7  *          |                |                |
     8  *          |                |<-- Ack --------+
     9  *          |                |                |
    10  *          |<-- Ack --------+                |
    11  *          |                |                |
    12  *          |                |                |
```

a more detailed view is...

```
    1   qdel                      pbs_server
    2   ----------------------    ------------------------
    3   pbsD_deljob()                (lib/Libifl/pbsD_deljob.c)
    4     PBSD_manager()             (lib/Libifl/PBSD_manager.c)
    5       PBSD_mgr_put()           (lib/Libifl/PBSD_manage2.c)
    6         DIS_tcp_wflush() -->
    7       PBSD_rdrpy()
    8 
    9 
   10                                         pbs_mom
   11                                         --------------------------
   12                                         main()                     (resmom/mom_main.c)
   13                                           finish_loop()            (resmom/mom_main.c)
   14                                             wait_request()         (lib/Libnet/net_server.c)
   15                                               accept_conn()
   16                                               obit_reply()         (resmom/catch_child.c)
   17                                               process_request()    (server/process_request.c)
   18                                                 dispatch_request() (server/process_request.c)
   19                                                   req_cpyfile
   20                                                   req_deletejob()  (resmom/requests.c)
   21                                                     mom_deljob()   (resmom/catch_child.c)
   22                                                       svr_job_purge()  (server/job_func.c)
   23                                                     reply_ack()
   24 
   25                             wait_request()                       (net_server.c)
   26                               process_request()                  (server/process_request.c)
   27                                 dis_request_read()               (server/dis_read.c)
   28                                   decode_DIS_RunJob()            (lib/Libifl/dec_RunJob.c)
   29                               dispatch_request()                 (server/process_request.c)
   30                                 req_deletejob()                  (server/req_delete.c)
   31                                   set_task()                     (server/svr_task.c)
   32                               dispatch_task()                    (server/svr_task.c)
   33                                     reply_text()                 (server/reply_send.c)
   34                                       reply_send()               (server/reply_send.c)
   35  *   PBSD_rdrpy      <-----
```

in particular when the `pbs_server` receives the `Ack` from `pbs_mom` the method `req_deletejob()` is called in `server/req_delete.c`.

This method walk through consists of...

```
req_deletejob()
  handle_single_delete()
    single_delete_work()
      execute_job_delete()
        chk_job_req_permissions() # server/svr_chk_owner.c
```

this method is where the `PBSE_BADSTATE` error is set. In particular here:

```c
  if (svr_authorize_jobreq(preq, pjob) == -1)
    {
      /* stuff... */
    }
  else if (pjob->ji_qs.ji_state >= JOB_STATE_EXITING)
    {
    /* job has completed */

    switch (preq->rq_type)
      {
      case PBS_BATCH_Rerun:
        /* allow re-run to be executed for completed jobs */
        /* NO-OP */
        break;
      default:
        sprintf(log_buf, "%s %s",
          pbse_to_txt(PBSE_BADSTATE),
          PJobState[pjob->ji_qs.ji_state]);

        log_event(PBSEVENT_DEBUG,PBS_EVENTCLASS_JOB,pjob->ji_qs.ji_jobid,log_buf);

        snprintf(tmpLine, sizeof(tmpLine), 
          "invalid state for job - %s",
          PJobState[pjob->ji_qs.ji_state]);

        req_reject(PBSE_BADSTATE, 0, preq, NULL, tmpLine);

        unlock_ji_mutex(pjob, __func__, "2", LOGLEVEL);

        *pjob_ptr = NULL;

        break;
      }  /* END switch (preq->rq_type) */
    }    /* END if (pjob->ji_qs.ji_state >= JOB_STATE_EXITING) */

  /* SUCCESS - request is valid */
```

Note that it is only set if the job state is `>= JOB_STATE_EXITING`. So we check the values for the various job states:

```c
# include/pbs_job.h

/* sync w/PJobState[] */

#define JOB_STATE_TRANSIT 0
#define JOB_STATE_QUEUED 1
#define JOB_STATE_HELD  2
#define JOB_STATE_WAITING 3
#define JOB_STATE_RUNNING 4
#define JOB_STATE_EXITING 5
#define JOB_STATE_COMPLETE 6
```

So this only includes the states `E` and `C`.

Note: This only covers the occurrence of `PBSE_BADSTATE` in `pbs_server`. There are cases of it occurring in `pbs_mom` but the code is quite complex there, and I am not quite sure how `pbs_mom` passes its error codes to  `pbs_server` in the Ack response. And if `pbs_server` repackages that error code, then I am not seeing it for `PBSE_BADSTATE`.

**Comment by nickjer** [comment]
After some perusing of the `pbs_mom` part of the code, I am feeling 80% confident that it doesn't return a `PBSE_BADSTATE` error for job deletion. I *believe* it will only return the error code `PBSE_UNKJOBID` if it cannot find the job to delete.

The relevant code is...

```c
/* resmom/requests.c */

void req_deletejob(

  struct batch_request *preq)  /* I */

  {
  job        *pjob;
  pjobexec_t *TJE = NULL;
  char        log_buf[LOCAL_LOG_BUF_SIZE];

  pjob = mom_find_job(preq->rq_ind.rq_delete.rq_objname);

  if (pjob != NULL)
    {
    /* stuff... */
    mom_deljob(pjob);
    reply_ack(preq);
    }
  else
    {
    req_reject(PBSE_UNKJOBID, 0, preq, mom_host, (char *)"cannot locate job to delete");
    }

  return;
  }  /* END req_deletejob() */
```

Where...

```
 * reply_ack()   - send a basic no error acknowledgement
 * req_reject()  - send a basic error return
```

**Comment by ericfranz** [comment]
Put a comment above the nil explaining why we rescue from these two errors:

```
rescue PBS::UnkjobidError, PBS::BadstateError
  nil
```

**Comment by nickjer** [comment]
Done in 832eac9a5fdd62417b1d8ef86406db6684cd6171
